In [ ]:
#1
import numpy as np
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#2
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#3
x = np.random.randint(10,10000,20)
print(x)
print('---------------')
y = x * 0.1
print(y)
print('---------------')
z = y ** 2
print(z)

[6527 6247   18 9852 8884 9147 6582 6649 5375 2595 7739  277 1144 4302
 2317 3115  140  287 6911 9477]
---------------
[652.7 624.7   1.8 985.2 888.4 914.7 658.2 664.9 537.5 259.5 773.9  27.7
 114.4 430.2 231.7 311.5  14.   28.7 691.1 947.7]
---------------
[4.2601729e+05 3.9025009e+05 3.2400000e+00 9.7061904e+05 7.8925456e+05
 8.3667609e+05 4.3322724e+05 4.4209201e+05 2.8890625e+05 6.7340250e+04
 5.9892121e+05 7.6729000e+02 1.3087360e+04 1.8507204e+05 5.3684890e+04
 9.7032250e+04 1.9600000e+02 8.2369000e+02 4.7761921e+05 8.9813529e+05]


In [ ]:
#4
x = np.random.randint(10,10000,20)
y = [(i * 0.1) ** 2 for i in x]
print(y)

[151009.96000000002, 554578.0900000001, 236098.81000000003, 387630.76, 19209.96, 10060.090000000002, 18333.16, 578664.4900000001, 825372.25, 401575.69000000006, 2798.4100000000008, 668469.76, 198916.0, 64211.560000000005, 293330.56, 861184.0, 132277.69000000003, 263682.25, 376504.96, 43932.16000000001]


In [ ]:
#5
import time
t1 = time.time()
x = np.random.randint(10,10000,20)
y = (x * 0.1) ** 2
t2 = time.time()
print(t2 - t1)
#print(y)

0.0005662441253662109


In [ ]:
t1 = time.time()
x = np.random.randint(10,10000,20)
y = [(i * 0.1) ** 2 for i in x]
t2 = time.time()
print(t2 - t1)
# print(y)

0.0015201568603515625


In [ ]:
np.random.rand(20)

array([0.88445713, 0.01834476, 0.24870341, 0.80698861, 0.18497049,
       0.35801286, 0.88384596, 0.11330595, 0.90554262, 0.55968234,
       0.8979132 , 0.29329081, 0.16917781, 0.80112399, 0.03984399,
       0.57506044, 0.37256373, 0.16190324, 0.54337438, 0.83118794])

In [ ]:
#6
np.linspace(10,10000)

array([   10.        ,   213.87755102,   417.75510204,   621.63265306,
         825.51020408,  1029.3877551 ,  1233.26530612,  1437.14285714,
        1641.02040816,  1844.89795918,  2048.7755102 ,  2252.65306122,
        2456.53061224,  2660.40816327,  2864.28571429,  3068.16326531,
        3272.04081633,  3475.91836735,  3679.79591837,  3883.67346939,
        4087.55102041,  4291.42857143,  4495.30612245,  4699.18367347,
        4903.06122449,  5106.93877551,  5310.81632653,  5514.69387755,
        5718.57142857,  5922.44897959,  6126.32653061,  6330.20408163,
        6534.08163265,  6737.95918367,  6941.83673469,  7145.71428571,
        7349.59183673,  7553.46938776,  7757.34693878,  7961.2244898 ,
        8165.10204082,  8368.97959184,  8572.85714286,  8776.73469388,
        8980.6122449 ,  9184.48979592,  9388.36734694,  9592.24489796,
        9796.12244898, 10000.        ])

In [ ]:
#7
np.arange(10,2000,2)

array([  10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98,  100,  102,  104,  106,  108,  110,  112,  114,  116,  118,
        120,  122,  124,  126,  128,  130,  132,  134,  136,  138,  140,
        142,  144,  146,  148,  150,  152,  154,  156,  158,  160,  162,
        164,  166,  168,  170,  172,  174,  176,  178,  180,  182,  184,
        186,  188,  190,  192,  194,  196,  198,  200,  202,  204,  206,
        208,  210,  212,  214,  216,  218,  220,  222,  224,  226,  228,
        230,  232,  234,  236,  238,  240,  242,  244,  246,  248,  250,
        252,  254,  256,  258,  260,  262,  264,  266,  268,  270,  272,
        274,  276,  278,  280,  282,  284,  286,  288,  290,  292,  294,
        296,  298,  300,  302,  304,  306,  308,  3

In [ ]:
#8
number = np.arange(12,900)
#print(number)
#mark = number % 2 != 0
#print(mark)
print(number[number % 2 != 0])

[ 13  15  17  19  21  23  25  27  29  31  33  35  37  39  41  43  45  47
  49  51  53  55  57  59  61  63  65  67  69  71  73  75  77  79  81  83
  85  87  89  91  93  95  97  99 101 103 105 107 109 111 113 115 117 119
 121 123 125 127 129 131 133 135 137 139 141 143 145 147 149 151 153 155
 157 159 161 163 165 167 169 171 173 175 177 179 181 183 185 187 189 191
 193 195 197 199 201 203 205 207 209 211 213 215 217 219 221 223 225 227
 229 231 233 235 237 239 241 243 245 247 249 251 253 255 257 259 261 263
 265 267 269 271 273 275 277 279 281 283 285 287 289 291 293 295 297 299
 301 303 305 307 309 311 313 315 317 319 321 323 325 327 329 331 333 335
 337 339 341 343 345 347 349 351 353 355 357 359 361 363 365 367 369 371
 373 375 377 379 381 383 385 387 389 391 393 395 397 399 401 403 405 407
 409 411 413 415 417 419 421 423 425 427 429 431 433 435 437 439 441 443
 445 447 449 451 453 455 457 459 461 463 465 467 469 471 473 475 477 479
 481 483 485 487 489 491 493 495 497 499 501 503 50

In [ ]:
#9
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#10
x=np.linspace(5,25,100)
#x = np.random.randint(5,25,100)
print(x)
print('***************')
for i in range(0,len(x)):
  diff = np.subtract(x[i], x[i+1])
  print(x[i] ,'-', x[i+1] ,'=',x[i] - x[i+1])

[ 5.          5.2020202   5.4040404   5.60606061  5.80808081  6.01010101
  6.21212121  6.41414141  6.61616162  6.81818182  7.02020202  7.22222222
  7.42424242  7.62626263  7.82828283  8.03030303  8.23232323  8.43434343
  8.63636364  8.83838384  9.04040404  9.24242424  9.44444444  9.64646465
  9.84848485 10.05050505 10.25252525 10.45454545 10.65656566 10.85858586
 11.06060606 11.26262626 11.46464646 11.66666667 11.86868687 12.07070707
 12.27272727 12.47474747 12.67676768 12.87878788 13.08080808 13.28282828
 13.48484848 13.68686869 13.88888889 14.09090909 14.29292929 14.49494949
 14.6969697  14.8989899  15.1010101  15.3030303  15.50505051 15.70707071
 15.90909091 16.11111111 16.31313131 16.51515152 16.71717172 16.91919192
 17.12121212 17.32323232 17.52525253 17.72727273 17.92929293 18.13131313
 18.33333333 18.53535354 18.73737374 18.93939394 19.14141414 19.34343434
 19.54545455 19.74747475 19.94949495 20.15151515 20.35353535 20.55555556
 20.75757576 20.95959596 21.16161616 21.36363636 21

IndexError: ignored

In [ ]:
#11
np.random.rand()

0.8929599602263341

In [ ]:
#12
x = np.random.randint(50,100,(4,4))
print(x)

[[93 89 67 76]
 [51 87 82 98]
 [80 64 75 71]
 [81 88 68 88]]


In [ ]:
x.T

array([[93, 51, 80, 81],
       [89, 87, 64, 88],
       [67, 82, 75, 68],
       [76, 98, 71, 88]])

In [ ]:
#13
import numpy as np
m1 = np.reshape(np.arange(1,26),(5,5))
print(m1)
print(m1[1:3,2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 8  9]
 [13 14]]


In [ ]:
#14
print(m1[3,2:])

[18 19 20]


In [ ]:
#15
print(m1[3:,:2])

[[16 17]
 [21 22]]


In [ ]:
#16
print(m1[3])

[16 17 18 19 20]


In [ ]:
#17
import numpy as np
m1 = np.reshape(np.arange(1,26),(5,5))
print(m1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#18 not finish
import numpy as np
x = np.random.randint(10,100,(5,5))
print(x)
for i in range(len(x)):
    for j in range(len(x)):
        if x[i][j] > 50:
            print("x({},{}) = {} more than 50".format(i, j,x[i][j]))


[[19 47 14 52 58]
 [91 20 46 35 94]
 [13 85 42 92 53]
 [30 32 52 29 50]
 [71 45 21 84 61]]
x(0,3) = 52 more than 50
x(0,4) = 58 more than 50
x(1,0) = 91 more than 50
x(1,4) = 94 more than 50
x(2,1) = 85 more than 50
x(2,3) = 92 more than 50
x(2,4) = 53 more than 50
x(3,2) = 52 more than 50
x(4,0) = 71 more than 50
x(4,3) = 84 more than 50
x(4,4) = 61 more than 50


In [ ]:
#19
x = np.random.randint(10,100,(5,5))
print(x)
print('-----------------------')
y = x[x > 40]
print(y)

[[91 53 17 31 95]
 [56 85 15 52 66]
 [18 68 94 65 37]
 [49 97 32 34 42]
 [18 97 74 11 94]]
-----------------------
[91 53 95 56 85 52 66 68 94 65 49 97 42 97 74 94]


In [ ]:
#20
import numpy as np
i = 1
lst_input = []
while len(lst_input) < 9:
    number = int(input('กรอกตัวเลขตัวที่ %d ( ช่วง 10 - 100 และไม่ซ้ำกัน) = ' %i))
    if number in lst_input:
        print('ตัวเลขต้องไม่ซ้ำกันกับ {} ใส่ตัวเลขใหม่ อีกครั้ง'.format(lst_input))
    elif number < 10 or number > 100:
        print('กรุณากรอกตัวเลขในช่วง 1 - 100')
    else:
        lst_input.append(number)
        i = i + 1
print(lst_input)
m = np.array(lst_input).reshape(3,3)
print('สมาชิกของของเมตริก คือ')
print(m)
mT = m.T
print('ผลการทราสโพส คือ')
print(mT)
print('ข้อมูลในตำแหน่ง แถวที่ 2 และ คอลัมภ์ที่่ 2 คือ',mT[2, 2])



กรอกตัวเลขตัวที่ 1 ( ช่วง 10 - 100 และไม่ซ้ำกัน) = 11
กรอกตัวเลขตัวที่ 2 ( ช่วง 10 - 100 และไม่ซ้ำกัน) = 22
กรอกตัวเลขตัวที่ 3 ( ช่วง 10 - 100 และไม่ซ้ำกัน) = 33
กรอกตัวเลขตัวที่ 4 ( ช่วง 10 - 100 และไม่ซ้ำกัน) = 44
กรอกตัวเลขตัวที่ 5 ( ช่วง 10 - 100 และไม่ซ้ำกัน) = 55
กรอกตัวเลขตัวที่ 6 ( ช่วง 10 - 100 และไม่ซ้ำกัน) = 66
กรอกตัวเลขตัวที่ 7 ( ช่วง 10 - 100 และไม่ซ้ำกัน) = 77
กรอกตัวเลขตัวที่ 8 ( ช่วง 10 - 100 และไม่ซ้ำกัน) = 88
กรอกตัวเลขตัวที่ 9 ( ช่วง 10 - 100 และไม่ซ้ำกัน) = 99
[11, 22, 33, 44, 55, 66, 77, 88, 99]
สมาชิกของของเมตริก คือ
[[11 22 33]
 [44 55 66]
 [77 88 99]]
ผลการทราสโพส คือ
[[11 44 77]
 [22 55 88]
 [33 66 99]]
ข้อมูลในตำแหน่ง แถวที่ 2 และ คอลัมภ์ที่่ 2 คือ 99
