In [ ]:
import pandas as pd
pd.__version__

'0.25.3'

In [ ]:
# การเก็บข้อมูลแบบ Series(1d array or vector)
import numpy as np
import pandas as pd

#แปลง dict เป็น Series
dict1 = {'Robert':90, 'John':99, 'Smith':85}
dict1
pd.Series(dict1)

Robert    90
John      99
Smith     85
dtype: int64

In [ ]:
#แปลง list เป็น Series
name = ['Robert', 'John', 'Smith']
score = [90, 99, 85]
series = pd.Series(data = score, index = name)
series

Robert    90
John      99
Smith     85
dtype: int64

In [ ]:
import pandas as pd

name = ['Robert', 'John', 'Smith']
score = [90, 99, 85]

series = pd.Series(score, name)
series

Robert    90
John      99
Smith     85
dtype: int64

In [ ]:
print(type(score))
print(type(name))

<class 'list'>
<class 'list'>


In [ ]:
#แปลง numpy array เป็น Sesies
name2 = np.array(name)
score2 = np.array(score)
print(name2)
print(score2)

['Robert' 'John' 'Smith']
[90 99 85]


In [ ]:
print(type(score2))
print(type(name2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
import pandas as pd

name2 = np.array(name)
score2 = np.array(score)
series2 = pd.Series(data = score2, index = name2)
series2

Robert    90
John      99
Smith     85
dtype: int64

In [ ]:
series2 = pd.Series(score2, name2)
series2

Robert    90
John      99
Smith     85
dtype: int64

In [ ]:
print(series2.index)

Index(['Robert', 'John', 'Smith'], dtype='object')


In [ ]:
print(series2.values)

[90 99 85]


In [ ]:
series2.values[0]

90

In [ ]:
series2.index[1]

'John'

In [ ]:
#Series เก็บข้อมูลต่างชนิดกันได้ ไม่เหมือน numpy array ที่ต้องเก็บข้อมูลลชนิดเดียวกันเท่านั้น
name = ['Robert', 'John', 'Smith']
score = [90, 'good', 85]

series = pd.Series(score, name)
series

Robert      90
John      good
Smith       85
dtype: object

In [ ]:
#ใส่ data และ index เข้า Series โดยตรง
series1 = pd.Series(data=['A','B','C'], index=[1,2,3])
series1

1    A
2    B
3    C
dtype: object

In [ ]:
#ถ้าไม่ระบุ index จะได้ index เป็น 1,2,3,...
#name = ['Robert', 'John', 'Smith']
score = [90, 'Well', 85]

series = pd.Series(score)
series

0      90
1    Well
2      85
dtype: object

In [ ]:
#การเข้าถึงข้อมูลของ Series
name = ['Robert', 'John', 'Smith']
score = [90, 99, 85]

series = pd.Series(score, name)
series

Robert    90
John      99
Smith     85
dtype: int64

In [ ]:
series['Robert'] #ใช้ index เป็นตัวอักษร

90

In [ ]:
series[0] #ใช้ index เป็นตัวเลข

90

In [ ]:
series[0:2] #ใช้ index เป็นช่วงตัวเลขต่อเนื่องกัน

Robert    90
John      99
dtype: int64

In [ ]:
series[1:3] #ใช้ index เป็นช่วงตัวเลขที่ต่อเนื่องกัน

John     99
Smith    85
dtype: int64

In [ ]:
import pandas as pd
name = ['Robert', 'John', 'Smith']
score = [90, 99, 85]

series = pd.Series(score, name)
series
series[[0,2]] #ใช้ index เป็นช่วงตัวเลขไม่ต่อเนื่องกัน

Robert    90
Smith     85
dtype: int64

In [ ]:
series[['Robert','Smith']] #ใช้ index เป็นตัวอักษรหลายกลุ่ม

Robert    90
Smith     85
dtype: int64

In [ ]:
import pandas as pd
name = ['Robert', 'John', 'Smith', 'Kim']
score = [90, 99, 85, 77]

series = pd.Series(score, name)
series
series[[True, False, True, False]] #ใช้ True เพื่อเลื่อก และใช้ False เมื่อไม่เลือก

Robert    90
Smith     85
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

name = ['Robert', 'John', 'Smith', 'Kim','Jim','Alex']
score = [90, 99, 85, 77, 55, 68]

series = pd.Series(score, name)
series

Robert    90
John      99
Smith     85
Kim       77
Jim       55
Alex      68
dtype: int64

In [ ]:
import numpy as np
number = np.arange(6)
print(number)

[0 1 2 3 4 5]


In [ ]:
number % 2 == 0

array([ True, False,  True, False,  True])

In [ ]:
series[number % 2 == 0] #ใช้การระบุเงื่อนไขเพื่อเลือกกลุ่มข้อมูล

Robert    90
Smith     85
Jim       55
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

name = ['Robert', 'John', 'Smith', 'Kim','Jim','Alex']
score = [90, 99, 85, 77, 55, 68]

series = pd.Series(data=score, index=name)
series

Robert    90
John      99
Smith     85
Kim       77
Jim       55
Alex      68
dtype: int64

In [ ]:
series.mean() #หาค่าเฉลี่ย

79.0

In [ ]:
series.max() #หาค่าสูงสุด

99

In [ ]:
series.min() #หาค่าต่ำสุด

55

In [ ]:
series.std() #หาค่าเบี่ยงเบนมาตรฐาน

15.861904047118681

In [ ]:
series.sum() #หาค่าผลรวม

474

In [ ]:
series.argmax() #หาค่าตำแหน่ง index ที่มีค่าสูงสุด

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: 
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  """Entry point for launching an IPython kernel.


'John'

In [ ]:
#จะเพิ่มข้อมูล เมื่อ index ไม่ซ้ำของเดิน
series['Peter'] = 15
series

Robert    90
John      99
Smith     85
Kim       77
Jim       55
Alex      68
Peter     15
dtype: int64

In [ ]:
#จะแก้ไขข้อมูล เมื่อ index ซ้ำของเดิน
series['Peter'] = 33
series

Robert    90
John      99
Smith     85
Kim       77
Jim       55
Alex      68
Peter     33
dtype: int64

In [ ]:
#การลบข้อมูล โดยระบุ index ของข้อมูลที่จะลบ
del series['Peter']
series

Robert    90
John      99
Smith     85
Kim       77
Jim       55
Alex      68
dtype: int64

In [ ]:
# การบวก Series กับ Series
import pandas as pd
import numpy as np

name1 = ['Robert', 'John', 'Smith']
score1 = [90, 99, 85]

series1 = pd.Series(data=score1, index=name1)
series1

Robert    90
John      99
Smith     85
dtype: int64

In [ ]:
name2 = ['Robert', 'John', 'Smith']
score2 = [56, 64, 65]

series2 = pd.Series(data=score2, index=name2)
series2

Robert    56
John      64
Smith     65
dtype: int64

In [ ]:
series1 + series2 # การบวก Series กับ Series ที่มี idex ตรงกัน

Robert    146
John      163
Smith     150
dtype: int64

In [ ]:
name3 = ['Robert', 'John', 'Smith', 'Kim']
score3 = [56, 64, 65, 99]

series3 = pd.Series(data=score3, index=name3)
series3

Robert    56
John      64
Smith     65
Kim       99
dtype: int64

In [ ]:
series2 + series3 # การบวก Series กับ Series ที่มี idex ตรงกัน แต่มีจำนวนข้อมูลไม่เท่ากันหรือ index ไม่เหมือนกัน อันที่ไม่มีคู่จะเกิด NaN(ไม่มีค่า)

John      128.0
Kim         NaN
Robert    112.0
Smith     130.0
dtype: float64

In [ ]:
# การเก็บข้อมูลแบบ DataFrame(2d array or matrix) คือ เก็บเป็นตาราง นำหลาย Series มาเรียงเป็นแถวแนวนอน
import pandas as pd
import numpy as np

value = np.random.randint(0,20,(3,3))
value


array([[12, 19, 11],
       [19, 11,  6],
       [ 5,  3, 10]])

In [ ]:
row = ['A', 'B', 'C']
column = ['X', 'Y', 'Z']
df = pd.DataFrame(value, row, column)
df

X   Y   Z
A  12  19  11
B  19  11   6
C   5   3  10

In [ ]:
print(df)

    X   Y   Z
A  12  19  11
B  19  11   6
C   5   3  10


In [ ]:
df.shape # ตรวจสอบมิติของ DataFrame เช่น (3,3) คือ 3 แถว 3 หลัก

(3, 3)

In [ ]:
df.X # เลือกข้อมูลในคอลัมภ์ X แบบนี้ไม่แนะนำ เพราะอาจสับสนกับการเรียกใช้ฟังก์ชั่นได้

A    12
B    19
C     5
Name: X, dtype: int64

In [ ]:
df['X'] # เลือกข้อมูลหนึ่งคอลัมภ์ เช่น X แบบนี้แนะนำ

A    12
B    19
C     5
Name: X, dtype: int64

In [ ]:
df[['X', 'Z']] # เลือกข้อมูลหลายคอลัมภ์ เช่น X และ Z แบบนี้แนะนำ

X   Z
A  12  11
B  19   6
C   5  10

In [ ]:
type(df['X'])

pandas.core.series.Series

In [ ]:
type(df[['X', 'Z']])

pandas.core.frame.DataFrame

In [ ]:
df

X   Y   Z
A  12  19  11
B  19  11   6
C   5   3  10

In [ ]:
df['P'] = [1, 2, 3] # เพิ่มคอลัมภ์ของ DataFrame
df

X   Y   Z  P
A  12  19  11  1
B  19  11   6  2
C   5   3  10  3

In [ ]:
df.drop('P', axis=1) # ลบคอลัมภ์ของ DataFrame จะกำหนด axis=1 เสมอ

X   Y   Z
A  12  19  11
B  19  11   6
C   5   3  10

In [ ]:
df.drop('A', axis=0) # ลบแถวของ DataFrame จะกำหนด axis=0

X   Y   Z  P
B  19  11   6  2
C   5   3  10  3

In [ ]:
df.drop('A') # ลบแถวของ DataFrame จะไม่กำหนด axis=0 ก็ได้

X   Y   Z  P
B  19  11   6  2
C   5   3  10  3